# Generated by Django 3.1 on 2020-08-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='records',
            field=models.CharField(max_length=800),
        ),
    ]
